name: Release
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install npm dependencies
        run: npm install
      
      - name: install expo
        run: npx install-expo-modules@latest

      - name: remove duplicate assets
        run: rm -rf ./android/app/src/main/res/raw/ && rm -rf ./android/app/src/main/res/drawable-mdpi/

      - name: Build Android APK
        run: cd android && ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: OverSlots
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload Android APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SLOTMACHINE_GITACTIONS }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android/app/build/outputs/apk/release/app-release.apk
          asset_name: OverSlots.apk