name: Release
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install npm dependencies
        run: npm install

      - name: Build Android APK
        run: cd android && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: OverSlots
          path: android/app/build/outputs/apk/release/app-release.apk
